USE [master]
GO

/****** Object:  Database [DEIG]    Script Date: 10/10/2016 10:26:12 AM ******/
CREATE DATABASE [DEIG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DEIG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DEIG.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DEIG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DEIG_log.ldf' , SIZE = 4672KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DEIG] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DEIG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DEIG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DEIG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DEIG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DEIG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DEIG] SET ARITHABORT OFF 
GO

ALTER DATABASE [DEIG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DEIG] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DEIG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DEIG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DEIG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DEIG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DEIG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DEIG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DEIG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DEIG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DEIG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DEIG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DEIG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DEIG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DEIG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DEIG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DEIG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DEIG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DEIG] SET RECOVERY FULL 
GO

ALTER DATABASE [DEIG] SET  MULTI_USER 
GO

ALTER DATABASE [DEIG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DEIG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DEIG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DEIG] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DEIG] SET  READ_WRITE 
GO

